site_name: pyspark-regression
site_description: pyspark-regression docs
site_author: Forrest Bajbek
repo_url: https://github.com/forrest-bajbek/pyspark-regression

nav:
    - 'index.md'
    - 'installation.md'
    - 'examples.md'
    - 'reference.md'

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format